import {
  LayoutGrid,
  Kanban,
  GraduationCap,
  CheckSquare,
  PlusCircle,
  MessageCircle,
  Zap,
  FileSignature,
  Bot,
  Users,
  BarChart3,
  Landmark,
  ShoppingBag,
  ArrowLeftRight,
  Lock,
  Calculator,
  Receipt,
  Package,
  Boxes,
  TrendingUp,
  Scale,
  SlidersHorizontal,
  BookOpen,
  ShoppingCart,
  DoorOpen,
  Wallet,
  CircleDollarSign,
  Building2,
  Plug,
  Smartphone,
  Clock,
} from 'lucide-react';

/** Lucide icons keyed by `iconKey` from naviMenu — sidebar, drawer e sheet "Mais". */
export const NAV_MENU_ICONS = {
  inicio: LayoutGrid,
  pipeline: Kanban,
  students: GraduationCap,
  tarefas: CheckSquare,
  conversas: MessageCircle,
  automacoes: Zap,
  agente: Bot,
  mensalidades: Users,
  aReceber: CircleDollarSign,
  aPagar: Wallet,
  contratos: FileSignature,
  caixa: Landmark,
  financeiro: Landmark,
  visaoGeralFinanceiro: LayoutGrid,
  loja: ShoppingBag,
  movimentacoes: ArrowLeftRight,
  previsao: TrendingUp,
  fechamento: Lock,
  conciliacao: Scale,
  extratoContabil: BookOpen,
  configuracaoFinanceira: SlidersHorizontal,
  contabilidade: Calculator,
  vendas: Receipt,
  novaVenda: ShoppingCart,
  novoLancamento: PlusCircle,
  produtos: Package,
  estoque: Boxes,
  relatorios: BarChart3,
  reports: BarChart3,
  catraca: DoorOpen,
  presenca: DoorOpen,
  newLead: PlusCircle,
  empresa: Building2,
  equipe: Users,
  integracoes: Plug,
  whatsapp: Smartphone,
  clock: Clock,
  horarios: Clock,
};

const FALLBACK_ICON = LayoutGrid;

export function getNavMenuIcon(iconKey) {
  if (!iconKey) return FALLBACK_ICON;
  return NAV_MENU_ICONS[iconKey] || FALLBACK_ICON;
}
