/** Entity class name (Base44) → Appwrite table id */
export const TABLE_MAP = {
  Agency: 'agencies',
  Client: 'clients',
  Service: 'services',
  Task: 'tasks',
  TimeEntry: 'time_entries',
  CyclePlan: 'cycle_plans',
  Brief: 'briefs',
  BriefingTemplate: 'briefing_templates',
  ApprovalRequest: 'approval_requests',
  Invite: 'invites',
  Profile: 'profiles',
  // Perfil Vivo / conhecimento do cliente
  ClientDocument: 'client_documents',
  LearningEntry: 'learning_entries',
  EvolutionEvent: 'evolution_events',
  FinancialKPI: 'financial_kpis',
  // Configuração padrão da empresa (campanhas mensais)
  Empresa: 'empresas',
  Notification: 'notifications',
  AuditLog: 'audit_logs',
  PublicBriefingToken: 'public_briefing_tokens',
  PublicBriefingResponse: 'public_briefing_responses',
  // Entregas e aprovações de material
  MaterialDelivery: 'material_deliveries',
  MaterialDeliveryVersion: 'material_delivery_versions',
  AgencyDriveConnection: 'agency_drive_connections',
};

export const PHASE1_TABLES = Object.values(TABLE_MAP);

/**
 * Indexed / typed columns per table. Everything else goes into `payload` JSON.
 *
 * LearningEntry: código legado filtra por `projectId` (= clientId).
 * Mantemos `projectId` e `clientId` indexados para alinhar schema novo e queries antigas.
 */
export const TABLE_COLUMNS = {
  profiles: ['agencyId', 'role', 'clientId', 'name', 'email', 'full_name', 'status'],
  agencies: ['agencyName', 'name', 'contactPhone', 'ownerEmail', 'status'],
  clients: ['agencyId', 'name', 'status', 'email', 'phone'],
  services: ['agencyId', 'clientId', 'name', 'status', 'is_template', 'is_active', 'category'],
  tasks: ['agencyId', 'clientId', 'serviceId', 'title', 'status', 'priority', 'dueDate', 'assigneeId'],
  time_entries: [
    'agencyId',
    'userId',
    'taskId',
    'serviceId',
    'deliverableId',
    'status',
    'startedAt',
  ],
  cycle_plans: ['agencyId', 'clientId', 'serviceId', 'status', 'title'],
  briefs: ['agencyId', 'clientId', 'projectId', 'empresaId', 'status', 'title'],
  briefing_templates: ['agencyId', 'name', 'isActive'],
  empresas: ['agencyId', 'clientId', 'nome'],
  notifications: ['agencyId', 'userId', 'type', 'subject', 'title'],
  audit_logs: ['agencyId', 'entity_type', 'entity_id', 'action', 'actor_id'],
  public_briefing_tokens: ['agencyId', 'clientId', 'serviceId', 'token', 'status', 'expiresAt'],
  public_briefing_responses: ['agencyId', 'clientId', 'tokenId', 'briefId', 'status'],
  approval_requests: [
    'agencyId',
    'clientId',
    'status',
    'token',
    'contentType',
    'contentId',
    'serviceId',
    'expiresAt',
  ],
  material_deliveries: [
    'agencyId',
    'clientId',
    'serviceId',
    'deliverableId',
    'taskId',
    'title',
    'description',
    'status',
    'latestVersionNumber',
    'currentVersionId',
    'approvedVersionId',
    'approvalRequestId',
    'driveFolderId',
    'createdBy',
    'archivedAt',
  ],
  material_delivery_versions: [
    'agencyId',
    'deliveryId',
    'versionNumber',
    'driveFileId',
    'driveFolderId',
    'fileName',
    'mimeType',
    'fileSize',
    'checksumSha256',
    'driveModifiedTime',
    'reviewStatus',
    'feedback',
    'createdBy',
    'submittedAt',
    'decidedAt',
    'reviewerName',
    'reviewerEmail',
    'decision',
    'idempotencyKey',
  ],
  agency_drive_connections: [
    'agencyId',
    'googleAccountId',
    'googleEmail',
    'encryptedRefreshToken',
    'rootFolderId',
    'status',
    'scopes',
    'connectedBy',
    'connectedAt',
    'lastRefreshAt',
    'revokedAt',
    'lastError',
  ],
  invites: ['agencyId', 'email', 'role', 'status'],
  client_documents: [
    'agencyId',
    'clientId',
    'serviceId',
    'title',
    'group',
    'status',
    'visibility',
  ],
  learning_entries: [
    'agencyId',
    'clientId',
    'projectId',
    'title',
    'status',
    'reviewed',
    'confidence_score',
  ],
  evolution_events: [
    'agencyId',
    'clientId',
    'serviceId',
    'title',
    'type',
    'impact',
    'date',
  ],
  financial_kpis: [
    'agencyId',
    'clientId',
    'serviceId',
    'name',
    'status',
    'is_current',
  ],
};

export const BOOLEAN_COLUMNS = new Set([
  'is_template',
  'is_active',
  'isActive',
  'active',
  'is_recurrence_template',
  'reconciled',
  'financial_tx_sync_pending',
  'reviewed',
  'is_current',
]);

export const DATETIME_COLUMNS = new Set([
  'dueDate',
  'startedAt',
  'endedAt',
  'settledAt',
  'updated_at',
  'reconciled_at',
  'expected_settlement_at',
  'paid_at',
  'issued_at',
  'imported_at',
  'date',
  'expiresAt',
  'archivedAt',
  'driveModifiedTime',
  'submittedAt',
  'decidedAt',
  'connectedAt',
  'lastRefreshAt',
  'revokedAt',
]);

/** Integer columns — pass through as numbers in entityAdapter. */
export const INTEGER_COLUMNS = new Set([
  'latestVersionNumber',
  'versionNumber',
  'fileSize',
]);
