import { TABLE_MAP } from './appwrite/tableMap';
import { createEntityAdapter, createStubEntity } from './appwrite/entityAdapter';
import { authAdapter } from './appwrite/authAdapter';

function entity(name) {
  const tableId = TABLE_MAP[name];
  if (!tableId) return createStubEntity(name);
  return createEntityAdapter(tableId);
}

export const Client = entity('Client');
export const Project = entity('Project');
export const Brief = entity('Brief');
export const Insights = entity('Insights');
export const LearningEntry = entity('LearningEntry');
export const Scope = entity('Scope');
export const BriefingVersion = entity('BriefingVersion');
export const AuditLog = entity('AuditLog');
export const ProjectMember = entity('ProjectMember');
export const Agency = entity('Agency');
export const Invite = entity('Invite');
export const Service = entity('Service');
export const ScopeItem = entity('ScopeItem');
export const CyclePlan = entity('CyclePlan');
export const WorkOrder = entity('WorkOrder');
export const EvolutionEvent = entity('EvolutionEvent');
export const PlaybookItem = entity('PlaybookItem');
export const Notification = entity('Notification');
export const NotificationPreference = entity('NotificationPreference');
export const ServiceRiskState = entity('ServiceRiskState');
export const Job = entity('Job');
export const AgentExecution = entity('AgentExecution');
export const PublicBriefingToken = entity('PublicBriefingToken');
export const PublicBriefingResponse = entity('PublicBriefingResponse');
export const BriefingTemplate = entity('BriefingTemplate');
export const SentimentAnalysis = entity('SentimentAnalysis');
export const SmartRecommendation = entity('SmartRecommendation');
export const ApprovalRequest = entity('ApprovalRequest');
export const Task = entity('Task');
export const UserStory = entity('UserStory');
export const UserFeedback = entity('UserFeedback');
export const SurveyResponse = entity('SurveyResponse');
export const UserExperienceMetric = entity('UserExperienceMetric');
export const ClientDocument = entity('ClientDocument');
export const FinancialKPI = entity('FinancialKPI');
export const SupportLibrary = entity('SupportLibrary');
export const ProjectTeam = entity('ProjectTeam');
export const NotificationTemplate = entity('NotificationTemplate');
export const NotificationDelivery = entity('NotificationDelivery');
export const KPIFormulaDefinition = entity('KPIFormulaDefinition');
export const ReportGenerationManifest = entity('ReportGenerationManifest');
export const IngestEnvelope = entity('IngestEnvelope');
export const ImportJob = entity('ImportJob');
export const ExternalRef = entity('ExternalRef');
export const DataReview = entity('DataReview');
export const MappingProfile = entity('MappingProfile');
export const DocumentExtraction = entity('DocumentExtraction');
export const User = authAdapter;
